compila : presentazione.tex
	pdflatex presentazione.tex && pdflatex presentazione.tex ; make clean;

clean :
	rm -rf *~ presentazione.out presentazione.aux presentazione.toc presentazione.log presentazione.snm presentazione.nav
